### ISSUE TITLE
Few issues and a question!

### ISSUE THREAD

**Issue by jacc** [SniperGER/ProudLock#1]
Hi there! This tweak is awesome, but I have some questions and a few issues.
- When pulling down to notification center, the time disappears.
- The lockscreen unlocks too fast too see the lock glyph change.
- The unlock glyph isn't smooth in the transition. Could you make it like the iPhone X where it turns into a pearl then unlocks?
- Your repo is BEAUTIFUL! Could I please get the source code? It's so nice. My twitter is @jvcks0n :)

**Comment by jacc** [comment]
![51410dfa-df80-4dfe-a4d5-134ad27783a1](https://user-images.githubusercontent.com/6956351/43274672-c836179c-90cd-11e8-81a4-a0a11bd3e94f.png)
Another issue, ProudLock messes up thr time in landscape mode.

**Comment by SniperGER** [comment]
Are you by any chance using the compiled .deb file inside the `packages` folder? I don't see any of the issues with the version on https://repo.festival.ml/

For the lock screen, I would recommend disabling "Rest to unlock" or whatever it's called. The repo version also shows the glyph when the passcode screen is visible, in which the animation is naturally faster. Not my decision.

And on iPhone X, the glyph does NOT change into that pearl glyph. The animation is unmodified from Apple and does appear exactly like this on iPhone X. For anything else, you'll have to use LatchKey.

**Comment by jacc** [comment]
I’ll go ahead and update. Another issue is that the music player will be pulled up over the clock unless there are notifications present.

**Comment by jacc** [comment]
Update is great! However, if you don't mind, could you update the source code so I can go ahead and on my end create a preference bundle to allow things such as moving the time up and down? When using LatchKey the time looks too smushed.

**Comment by SniperGER** [comment]
Source code is now the current update 0.1-2. If you'd like to merge your preference bundle with the main project, please use the included icons.
